/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) battery_learned_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[7] = {2, 2, 0, 1, 2, 0, 0};
static const casadi_int casadi_s1[7] = {2, 2, 0, 2, 2, 0, 1};
static const casadi_int casadi_s2[3] = {2, 1, 1};
static const casadi_int casadi_s3[3] = {2, 2, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[5] = {2, 2, 0, 0, 0};

/* battery_learned_expl_vde_forw:(i0[2],i1[2x2],i2[2x2],i3[2],i4)->(o0[2],o1[2x2,0nz],o2[2x2,2nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+8, *w9=w+10;
  const casadi_real *cs;
  /* #0: @0 = 4.08805e-06 */
  w0 = 4.0880503144654089e-06;
  /* #1: @1 = 1.024 */
  w1 = 1.0240000000000000e+00;
  /* #2: @2 = input[4][0] */
  w2 = arg[4] ? arg[4][0] : 0;
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @1 = (@1*@3) */
  w1 *= w3;
  /* #5: @3 = 0.0001 */
  w3 = 1.0000000000000000e-04;
  /* #6: @4 = 0.00668451 */
  w4 = 6.6845076098596048e-03;
  /* #7: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #8: @5 = (@4*@5) */
  w5  = (w4*w5);
  /* #9: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #10: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #11: @7 = (@5*@6) */
  w7  = (w5*w6);
  /* #12: @1 = (@1+@7) */
  w1 += w7;
  /* #13: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #14: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #15: @1 = 100800 */
  w1 = 100800.;
  /* #16: @2 = (@2/@1) */
  w2 /= w1;
  /* #17: @2 = (-@2) */
  w2 = (- w2 );
  /* #18: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #19: @8 = zeros(2x2,2nz) */
  casadi_clear(w8, 2);
  /* #20: @2 = ones(2x1,1nz) */
  w2 = 1.;
  /* #21: {@1, NULL} = vertsplit(@2) */
  w1 = w2;
  /* #22: @4 = (@4*@1) */
  w4 *= w1;
  /* #23: @3 = (@3*@4) */
  w3 *= w4;
  /* #24: @6 = (@6*@3) */
  w6 *= w3;
  /* #25: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #26: (@8[0] = @6) */
  for (rr=w8+0, cs=(&w6); rr!=w8+1; rr+=1) *rr = *cs++;
  /* #27: @6 = ones(2x1,1nz) */
  w6 = 1.;
  /* #28: {NULL, @3} = vertsplit(@6) */
  w3 = w6;
  /* #29: @5 = (@5*@3) */
  w5 *= w3;
  /* #30: @0 = (@0*@5) */
  w0 *= w5;
  /* #31: (@8[1] = @0) */
  for (rr=w8+1, cs=(&w0); rr!=w8+2; rr+=1) *rr = *cs++;
  /* #32: @9 = @8' */
  casadi_trans(w8,casadi_s1, w9, casadi_s0, iw);
  /* #33: output[2][0] = @9 */
  casadi_copy(w9, 2, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_learned_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_learned_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void battery_learned_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void battery_learned_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int battery_learned_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int battery_learned_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real battery_learned_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_learned_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_learned_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_learned_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s3;
    case 3: return casadi_s2;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_learned_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s5;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 12;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 12*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
