/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) battery_learned_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};

/* battery_learned_expl_ode_fun:(i0[2],i1[2],i2)->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5;
  /* #0: @0 = 4.08805e-06 */
  w0 = 4.0880503144654089e-06;
  /* #1: @1 = 1.024 */
  w1 = 1.0240000000000000e+00;
  /* #2: @2 = input[2][0] */
  w2 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @1 = (@1*@3) */
  w1 *= w3;
  /* #5: @3 = 0.0001 */
  w3 = 1.0000000000000000e-04;
  /* #6: @4 = 0.00668451 */
  w4 = 6.6845076098596048e-03;
  /* #7: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #8: @4 = (@4*@5) */
  w4 *= w5;
  /* #9: @3 = (@3*@4) */
  w3 *= w4;
  /* #10: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #11: @3 = (@3*@4) */
  w3 *= w4;
  /* #12: @1 = (@1+@3) */
  w1 += w3;
  /* #13: @0 = (@0*@1) */
  w0 *= w1;
  /* #14: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #15: @0 = 100800 */
  w0 = 100800.;
  /* #16: @2 = (@2/@0) */
  w2 /= w0;
  /* #17: @2 = (-@2) */
  w2 = (- w2 );
  /* #18: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_learned_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_learned_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void battery_learned_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void battery_learned_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int battery_learned_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int battery_learned_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real battery_learned_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_learned_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_learned_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_learned_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_learned_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_learned_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 6*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
