/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cascaded_learned_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[9] = 
  {2, 2, 0, 2, 4, 0, 1, 0,
  1};
static const casadi_int casadi_s1[9] = 
  {3, 2, 0, 2, 4, 0, 1, 0,
  1};
static const casadi_int casadi_s2[12] = 
  {2, 3, 0, 2, 4, 6, 0, 1,
  0, 1, 0, 1};
static const casadi_int casadi_s3[5] = {2, 1, 0, 1, 0};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s5[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s6[6] = {3, 1, 0, 2, 0, 1};
static const casadi_int casadi_s7[3] = {2, 1, 1};
static const casadi_int casadi_s8[3] = {2, 2, 1};
static const casadi_int casadi_s9[3] = {1, 1, 1};

/* External functions */
int cascadedtank(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int jac_cascadedtank(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* cascadedtank:(i0[1x3])->(o0[1x2]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (cascadedtank(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* jac_cascadedtank:(i0[1x3],out_o0[1x2,0nz])->(jac_o0_i0[2x3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (jac_cascadedtank(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* cascaded_learned_expl_vde_forw:(i0[2],i1[2x2],i2[2],i3,i4)->(o0[2],o1[2x2],o2[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real *w10=w+12, *w11=w+14, *w12=w+17, *w13=w+19, *w15=w+23, *w16=w+29, *w17=w+31, *w18=w+35;
  const casadi_real **arg1=arg+5, *cs;
  /* #0: @0 = 1000 */
  w00 = 1000.;
  /* #1: @1 = input[3][0] */
  w01 = arg[3] ? arg[3][0] : 0;
  /* #2: @2 = (@0*@1) */
  w02  = (w00*w01);
  /* #3: @2 = (@2/@0) */
  w02 /= w00;
  /* #4: @0 = 0.1 */
  w00 = 1.0000000000000001e-01;
  /* #5: @3 = 1e-05 */
  w03 = 1.0000000000000001e-05;
  /* #6: @4 = 19.64 */
  w04 = 1.9640000000000001e+01;
  /* #7: @5 = input[0][0] */
  w05 = arg[0] ? arg[0][0] : 0;
  /* #8: @6 = (@4*@5) */
  w06  = (w04*w05);
  /* #9: @6 = (@3+@6) */
  w06  = (w03+w06);
  /* #10: @6 = sqrt(@6) */
  w06 = sqrt( w06 );
  /* #11: @7 = (@0*@6) */
  w07  = (w00*w06);
  /* #12: @2 = (@2-@7) */
  w02 -= w07;
  /* #13: @8 = input[4][0] */
  w08 = arg[4] ? arg[4][0] : 0;
  /* #14: @2 = (@2+@8) */
  w02 += w08;
  /* #15: @8 = input[0][1] */
  w08 = arg[0] ? arg[0][1] : 0;
  /* #16: @9 = (@4*@8) */
  w09  = (w04*w08);
  /* #17: @3 = (@3+@9) */
  w03 += w09;
  /* #18: @3 = sqrt(@3) */
  w03 = sqrt( w03 );
  /* #19: @9 = (@0*@3) */
  w09  = (w00*w03);
  /* #20: @7 = (@7-@9) */
  w07 -= w09;
  /* #21: @10 = vertcat(@2, @7) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w07;
  /* #22: @11 = vertcat(@5, @8, @1) */
  rr=w11;
  *rr++ = w05;
  *rr++ = w08;
  *rr++ = w01;
  /* #23: @11 = @11' */
  /* #24: @12 = cascadedtank(@11) */
  arg1[0]=w11;
  res1[0]=w12;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #25: @12 = @12' */
  /* #26: @5 = @12[0] */
  for (rr=(&w05), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #27: @8 = @12[1] */
  for (rr=(&w08), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #28: @12 = vertcat(@5, @8) */
  rr=w12;
  *rr++ = w05;
  *rr++ = w08;
  /* #29: @10 = (@10+@12) */
  for (i=0, rr=w10, cs=w12; i<2; ++i) (*rr++) += (*cs++);
  /* #30: output[0][0] = @10 */
  casadi_copy(w10, 2, res[0]);
  /* #31: @13 = input[1][0] */
  casadi_copy(arg[1], 4, w13);
  /* #32: {@10, @12} = horzsplit(@13) */
  casadi_copy(w13, 2, w10);
  casadi_copy(w13+2, 2, w12);
  /* #33: {@5, @8} = vertsplit(@10) */
  w05 = w10[0];
  w08 = w10[1];
  /* #34: @1 = (@4*@5) */
  w01  = (w04*w05);
  /* #35: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #36: @1 = (@1/@6) */
  w01 /= w06;
  /* #37: @1 = (@0*@1) */
  w01  = (w00*w01);
  /* #38: @2 = (-@1) */
  w02 = (- w01 );
  /* #39: @7 = (@4*@8) */
  w07  = (w04*w08);
  /* #40: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #41: @7 = (@7/@3) */
  w07 /= w03;
  /* #42: @7 = (@0*@7) */
  w07  = (w00*w07);
  /* #43: @1 = (@1-@7) */
  w01 -= w07;
  /* #44: @10 = vertcat(@2, @1) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w01;
  /* #45: @13 = zeros(2x2) */
  casadi_clear(w13, 4);
  /* #46: @14 = zeros(1x2,0nz) */
  /* #47: @15 = jac_cascadedtank(@11, @14) */
  arg1[0]=w11;
  arg1[1]=0;
  res1[0]=w15;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #48: @14 = 00 */
  /* #49: @16 = vertcat(@5, @8, @14) */
  rr=w16;
  *rr++ = w05;
  *rr++ = w08;
  /* #50: {@5, @8} = vertsplit(@12) */
  w05 = w12[0];
  w08 = w12[1];
  /* #51: @12 = vertcat(@5, @8, @14) */
  rr=w12;
  *rr++ = w05;
  *rr++ = w08;
  /* #52: @17 = horzcat(@16, @12) */
  rr=w17;
  for (i=0, cs=w16; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  /* #53: @13 = mac(@15,@17,@13) */
  casadi_mtimes(w15, casadi_s2, w17, casadi_s1, w13, casadi_s0, w, 0);
  /* #54: {@16, @12} = horzsplit(@13) */
  casadi_copy(w13, 2, w16);
  casadi_copy(w13+2, 2, w12);
  /* #55: @2 = @16[0] */
  for (rr=(&w02), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #56: @1 = @16[1] */
  for (rr=(&w01), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #57: @16 = vertcat(@2, @1) */
  rr=w16;
  *rr++ = w02;
  *rr++ = w01;
  /* #58: @10 = (@10+@16) */
  for (i=0, rr=w10, cs=w16; i<2; ++i) (*rr++) += (*cs++);
  /* #59: output[1][0] = @10 */
  casadi_copy(w10, 2, res[1]);
  /* #60: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #61: @5 = (@5/@6) */
  w05 /= w06;
  /* #62: @5 = (@0*@5) */
  w05  = (w00*w05);
  /* #63: @2 = (-@5) */
  w02 = (- w05 );
  /* #64: @8 = (@4*@8) */
  w08  = (w04*w08);
  /* #65: @8 = (@8/@3) */
  w08 /= w03;
  /* #66: @8 = (@0*@8) */
  w08  = (w00*w08);
  /* #67: @5 = (@5-@8) */
  w05 -= w08;
  /* #68: @10 = vertcat(@2, @5) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w05;
  /* #69: @2 = @12[0] */
  for (rr=(&w02), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #70: @5 = @12[1] */
  for (rr=(&w05), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #71: @12 = vertcat(@2, @5) */
  rr=w12;
  *rr++ = w02;
  *rr++ = w05;
  /* #72: @10 = (@10+@12) */
  for (i=0, rr=w10, cs=w12; i<2; ++i) (*rr++) += (*cs++);
  /* #73: output[1][1] = @10 */
  if (res[1]) casadi_copy(w10, 2, res[1]+2);
  /* #74: @10 = zeros(1x2) */
  casadi_clear(w10, 2);
  /* #75: @2 = 1 */
  w02 = 1.;
  /* #76: @5 = vertcat(@2, @14) */
  rr=(&w05);
  *rr++ = w02;
  /* #77: @12 = dense(@5) */
  casadi_densify((&w05), casadi_s3, w12, 0);
  /* #78: @16 = zeros(2x1) */
  casadi_clear(w16, 2);
  /* #79: @5 = vertcat(@14, @14, @2) */
  rr=(&w05);
  *rr++ = w02;
  /* #80: @18 = mac(@15,@5,@16) */
  casadi_copy(w16, 2, w18);
  casadi_mtimes(w15, casadi_s2, (&w05), casadi_s5, w18, casadi_s4, w, 0);
  /* #81: @5 = @18[0] */
  for (rr=(&w05), cs=w18+0; cs!=w18+1; cs+=1) *rr++ = *cs;
  /* #82: @2 = @18[1] */
  for (rr=(&w02), cs=w18+1; cs!=w18+2; cs+=1) *rr++ = *cs;
  /* #83: @18 = vertcat(@5, @2) */
  rr=w18;
  *rr++ = w05;
  *rr++ = w02;
  /* #84: @12 = (@12+@18) */
  for (i=0, rr=w12, cs=w18; i<2; ++i) (*rr++) += (*cs++);
  /* #85: (@10[:2] = @12) */
  for (rr=w10+0, cs=w12; rr!=w10+2; rr+=1) *rr = *cs++;
  /* #86: @10 = @10' */
  /* #87: @12 = input[2][0] */
  casadi_copy(arg[2], 2, w12);
  /* #88: {@5, @2} = vertsplit(@12) */
  w05 = w12[0];
  w02 = w12[1];
  /* #89: @8 = (@4*@5) */
  w08  = (w04*w05);
  /* #90: @8 = (@8/@6) */
  w08 /= w06;
  /* #91: @8 = (@0*@8) */
  w08  = (w00*w08);
  /* #92: @6 = (-@8) */
  w06 = (- w08 );
  /* #93: @4 = (@4*@2) */
  w04 *= w02;
  /* #94: @4 = (@4/@3) */
  w04 /= w03;
  /* #95: @0 = (@0*@4) */
  w00 *= w04;
  /* #96: @8 = (@8-@0) */
  w08 -= w00;
  /* #97: @12 = vertcat(@6, @8) */
  rr=w12;
  *rr++ = w06;
  *rr++ = w08;
  /* #98: @18 = vertcat(@5, @2, @14) */
  rr=w18;
  *rr++ = w05;
  *rr++ = w02;
  /* #99: @16 = mac(@15,@18,@16) */
  casadi_mtimes(w15, casadi_s2, w18, casadi_s6, w16, casadi_s4, w, 0);
  /* #100: @5 = @16[0] */
  for (rr=(&w05), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #101: @2 = @16[1] */
  for (rr=(&w02), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #102: @16 = vertcat(@5, @2) */
  rr=w16;
  *rr++ = w05;
  *rr++ = w02;
  /* #103: @12 = (@12+@16) */
  for (i=0, rr=w12, cs=w16; i<2; ++i) (*rr++) += (*cs++);
  /* #104: @10 = (@10+@12) */
  for (i=0, rr=w10, cs=w12; i<2; ++i) (*rr++) += (*cs++);
  /* #105: output[2][0] = @10 */
  casadi_copy(w10, 2, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cascaded_learned_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cascaded_learned_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real cascaded_learned_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cascaded_learned_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cascaded_learned_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cascaded_learned_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s7;
    case 3: return casadi_s9;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cascaded_learned_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 37;
  return 0;
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 37*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
