/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cascaded_learned_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};

/* External functions */
int cascadedtank(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* cascadedtank:(i0[1x3])->(o0[1x2]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (cascadedtank(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* cascaded_learned_expl_ode_fun:(i0[2],i1,i2)->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, *w08=w+8, *w09=w+10;
  casadi_real *w10=w+13;
  const casadi_real **arg1=arg+3, *cs;
  /* #0: @0 = 1000 */
  w00 = 1000.;
  /* #1: @1 = input[1][0] */
  w01 = arg[1] ? arg[1][0] : 0;
  /* #2: @2 = (@0*@1) */
  w02  = (w00*w01);
  /* #3: @2 = (@2/@0) */
  w02 /= w00;
  /* #4: @0 = 0.1 */
  w00 = 1.0000000000000001e-01;
  /* #5: @3 = 1e-05 */
  w03 = 1.0000000000000001e-05;
  /* #6: @4 = 19.64 */
  w04 = 1.9640000000000001e+01;
  /* #7: @5 = input[0][0] */
  w05 = arg[0] ? arg[0][0] : 0;
  /* #8: @6 = (@4*@5) */
  w06  = (w04*w05);
  /* #9: @6 = (@3+@6) */
  w06  = (w03+w06);
  /* #10: @6 = sqrt(@6) */
  w06 = sqrt( w06 );
  /* #11: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #12: @2 = (@2-@6) */
  w02 -= w06;
  /* #13: @7 = input[2][0] */
  w07 = arg[2] ? arg[2][0] : 0;
  /* #14: @2 = (@2+@7) */
  w02 += w07;
  /* #15: @7 = input[0][1] */
  w07 = arg[0] ? arg[0][1] : 0;
  /* #16: @4 = (@4*@7) */
  w04 *= w07;
  /* #17: @3 = (@3+@4) */
  w03 += w04;
  /* #18: @3 = sqrt(@3) */
  w03 = sqrt( w03 );
  /* #19: @0 = (@0*@3) */
  w00 *= w03;
  /* #20: @6 = (@6-@0) */
  w06 -= w00;
  /* #21: @8 = vertcat(@2, @6) */
  rr=w08;
  *rr++ = w02;
  *rr++ = w06;
  /* #22: @9 = vertcat(@5, @7, @1) */
  rr=w09;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w01;
  /* #23: @9 = @9' */
  /* #24: @10 = cascadedtank(@9) */
  arg1[0]=w09;
  res1[0]=w10;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #25: @10 = @10' */
  /* #26: @5 = @10[0] */
  for (rr=(&w05), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #27: @7 = @10[1] */
  for (rr=(&w07), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #28: @10 = vertcat(@5, @7) */
  rr=w10;
  *rr++ = w05;
  *rr++ = w07;
  /* #29: @8 = (@8+@10) */
  for (i=0, rr=w08, cs=w10; i<2; ++i) (*rr++) += (*cs++);
  /* #30: output[0][0] = @8 */
  casadi_copy(w08, 2, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cascaded_learned_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int cascaded_learned_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cascaded_learned_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cascaded_learned_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cascaded_learned_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cascaded_learned_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cascaded_learned_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 15;
  return 0;
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 15*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
