/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cascaded_learned_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};

/* External functions */
int adj1_cascadedtank(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* adj1_cascadedtank:(i0[1x3],out_o0[1x2,0nz],adj_o0[1x2])->(adj_i0[1x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (adj1_cascadedtank(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* cascaded_learned_expl_vde_adj:(i0[2],i1[2],i2,i3)->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, w00, w01, w02, *w03=w+3, *w05=w+6, *w06=w+8, w07, *w08=w+11, w09, w10;
  casadi_real w11, w12, w13, w14, w15;
  const casadi_real **arg1=arg+4, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w01 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[2][0] */
  w02 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = vertcat(@0, @1, @2) */
  rr=w03;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  /* #4: @3 = @3' */
  /* #5: @4 = zeros(1x2,0nz) */
  /* #6: @5 = zeros(2x1) */
  casadi_clear(w05, 2);
  /* #7: @6 = input[1][0] */
  casadi_copy(arg[1], 2, w06);
  /* #8: {@2, @7} = vertsplit(@6) */
  w02 = w06[0];
  w07 = w06[1];
  /* #9: (@5[1] += @7) */
  for (rr=w05+1, cs=(&w07); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #10: (@5[0] += @2) */
  for (rr=w05+0, cs=(&w02); rr!=w05+1; rr+=1) *rr += *cs++;
  /* #11: @5 = @5' */
  /* #12: @8 = adj1_cascadedtank(@3, @4, @5) */
  arg1[0]=w03;
  arg1[1]=0;
  arg1[2]=w05;
  res1[0]=w08;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #13: @8 = @8' */
  /* #14: {@9, @10, @11} = vertsplit(@8) */
  w09 = w08[0];
  w10 = w08[1];
  w11 = w08[2];
  /* #15: @12 = 19.64 */
  w12 = 1.9640000000000001e+01;
  /* #16: @13 = 0.1 */
  w13 = 1.0000000000000001e-01;
  /* #17: @7 = (@13*@7) */
  w07  = (w13*w07);
  /* #18: @14 = 1e-05 */
  w14 = 1.0000000000000001e-05;
  /* #19: @0 = (@12*@0) */
  w00  = (w12*w00);
  /* #20: @0 = (@14+@0) */
  w00  = (w14+w00);
  /* #21: @0 = sqrt(@0) */
  w00 = sqrt( w00 );
  /* #22: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #23: @15 = (@7/@0) */
  w15  = (w07/w00);
  /* #24: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #25: @9 = (@9+@15) */
  w09 += w15;
  /* #26: @13 = (@13*@2) */
  w13 *= w02;
  /* #27: @13 = (@13/@0) */
  w13 /= w00;
  /* #28: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #29: @9 = (@9-@13) */
  w09 -= w13;
  /* #30: output[0][0] = @9 */
  if (res[0]) res[0][0] = w09;
  /* #31: @1 = (@12*@1) */
  w01  = (w12*w01);
  /* #32: @14 = (@14+@1) */
  w14 += w01;
  /* #33: @14 = sqrt(@14) */
  w14 = sqrt( w14 );
  /* #34: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #35: @7 = (@7/@14) */
  w07 /= w14;
  /* #36: @12 = (@12*@7) */
  w12 *= w07;
  /* #37: @10 = (@10-@12) */
  w10 -= w12;
  /* #38: output[0][1] = @10 */
  if (res[0]) res[0][1] = w10;
  /* #39: @10 = 1000 */
  w10 = 1000.;
  /* #40: @12 = 0.001 */
  w12 = 1.0000000000000000e-03;
  /* #41: @12 = (@12*@2) */
  w12 *= w02;
  /* #42: @10 = (@10*@12) */
  w10 *= w12;
  /* #43: @11 = (@11+@10) */
  w11 += w10;
  /* #44: output[0][2] = @11 */
  if (res[0]) res[0][2] = w11;
  return 0;
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void cascaded_learned_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cascaded_learned_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int cascaded_learned_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cascaded_learned_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cascaded_learned_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cascaded_learned_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cascaded_learned_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cascaded_learned_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 21;
  return 0;
}

CASADI_SYMBOL_EXPORT int cascaded_learned_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 21*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
