function f = dynamics(t,in2,in3,p)
%DYNAMICS
%    F = DYNAMICS(T,IN2,IN3,P)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    17-Mar-2026 15:10:31

u1 = in3(1,:);
u2 = in3(2,:);
x1 = in2(1,:);
t2 = u1.*2.339577663450862e+1;
t3 = t2+1.0./1.0e+3;
t4 = 1.0./t3;
t5 = t4.*2.45259e+3;
t6 = -t5;
t7 = exp(t6);
t8 = t7-1.0;
t9 = 1.0./t8;
et1 = x1.*(-3.048816972981132e-5)-u1.*(t4.*t9.*u2-t4.*t7.*t9.*u2.*9.806820000000001e-1).*9.387268445260499e-5;
et2 = p.^2.*4.10867441509434e-6+8.022961864399849e-3;
f = [et1+et2;p.*(-9.920634920634921e-6)];
end
