function f = dynamics(t,in2,in3,in4)
%DYNAMICS
%    F = DYNAMICS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Mar-2026 17:29:28

p1 = in4(1,:);
u1 = in3(1,:);
u2 = in3(2,:);
x1 = in2(1,:);
t2 = u1.*2.339577663450862e+1;
t3 = t2+1.0./1.0e+3;
t4 = 1.0./t3;
t5 = t4.*2.5e+3;
t6 = -t5;
t7 = exp(t6);
t8 = t7-1.0;
t9 = 1.0./t8;
t10 = t4.*t9.*u2.*9.98321e-1;
et1 = u1.*(t10+x1.*1.27199999999994e-3-t7.*(t10+x1.*1.678999999999986e-3).*9.99593e-1).*(-9.564311202786542e-5);
et2 = p1.^2.*4.186163522012579e-6;
f = [et1+et2;p1.*(-9.920634920634921e-6)];
end
