%% Opening simulink model and importing python code
% Autogenerated folders, removing them is good practice, 
% especially when debugging
rmdir("_l4c_generated/",'s')
rmdir("c_generated_code/", 's') % Remember to uncomment when debugging
% Opening BTM
open("Adaptive_Cool_and_Heat_EVBatteryCoolingSystem.slx")
T_env = 36;
T_init = T_env + 273.15;
tF = 3*2474;
t_sim = tF;
% Importing python modules
adaptive_derivative_loss  = py.importlib.import_module('adaptive_derivative_loss_mpc_battery');
adaptive_trajectory_loss  = py.importlib.import_module('adaptive_trajectory_loss_mpc_battery');
nominal = py.importlib.import_module('nominal_acados_mpc_battery_new_scaling');

economic = py.importlib.import_module('nominal_economic_mpc_battery_new_scaling')
adaptive_economic_trajectory_loss = py.importlib.import_module('adaptive_economic_trajectory_loss');

%% Reloading python code
% When python code is imported in Matlab, it is imported "statically"
% If you make changes to the code, then these will not take effect
% Need to reload for the changes to appear
clear adaptive, clear nominal, clear lms, clear economic, clear adaptive_derivative_loss, clear adaptive_trajectory_loss, clear adaptive_economic_trajectory_loss
% Uncomment if debugging and not rerunning the above section
% Will error if these folders to not exist
%rmdir("_l4c_generated/", 's')
%rmdir("c_generated_code/", 's')
% Importing python modules

adaptive_derivative_loss  = py.importlib.import_module('adaptive_derivative_loss_mpc_battery');
adaptive_trajectory_loss  = py.importlib.import_module('adaptive_trajectory_loss_mpc_battery');
nominal = py.importlib.import_module('nominal_acados_mpc_battery_new_scaling');

economic = py.importlib.import_module('nominal_economic_mpc_battery_new_scaling');
adaptive_economic_trajectory_loss = py.importlib.import_module('adaptive_economic_trajectory_loss');
% Reloading python modules
py.importlib.reload(adaptive_derivative_loss)
py.importlib.reload(nominal)
py.importlib.reload(economic)
py.importlib.reload(adaptive_trajectory_loss)
py.importlib.reload(adaptive_economic_trajectory_loss)