/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) battery_learned_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[11] = 
  {4, 2, 0, 3, 6, 0, 1, 2,
  0, 1, 2};
static const casadi_int casadi_s3[3] = {2, 0, 1};

/* battery_learned_constr_h_fun_jac_uxt_zt:(i0[2],i1[2],i2[0],i3[2])->(o0[2],o1[4x2,6nz],o2[2x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, *w13=w+13, *w14=w+19;
  const casadi_real *cs;
  /* #0: @0 = 0.99 */
  w00 = 9.8999999999999999e-01;
  /* #1: @1 = input[0][0] */
  w01 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[1][1] */
  w02 = arg[1] ? arg[1][1] : 0;
  /* #3: @3 = 1 */
  w03 = 1.;
  /* #4: @4 = 2500 */
  w04 = 2500.;
  /* #5: @5 = 0.001 */
  w05 = 1.0000000000000000e-03;
  /* #6: @6 = 3500 */
  w06 = 3500.;
  /* #7: @7 = 0.00668451 */
  w07 = 6.6845076098596048e-03;
  /* #8: @8 = input[1][0] */
  w08 = arg[1] ? arg[1][0] : 0;
  /* #9: @8 = (@7*@8) */
  w08  = (w07*w08);
  /* #10: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #11: @5 = (@5+@8) */
  w05 += w08;
  /* #12: @4 = (@4/@5) */
  w04 /= w05;
  /* #13: @8 = (-@4) */
  w08 = (- w04 );
  /* #14: @8 = exp(@8) */
  w08 = exp( w08 );
  /* #15: @3 = (@3-@8) */
  w03 -= w08;
  /* #16: @2 = (@2/@3) */
  w02 /= w03;
  /* #17: @9 = (@2/@5) */
  w09  = (w02/w05);
  /* #18: @10 = (@1+@9) */
  w10  = (w01+w09);
  /* #19: @10 = (@0*@10) */
  w10  = (w00*w10);
  /* #20: output[0][0] = @10 */
  if (res[0]) res[0][0] = w10;
  /* #21: @11 = 0.97 */
  w11 = 9.6999999999999997e-01;
  /* #22: @10 = (@10-@1) */
  w10 -= w01;
  /* #23: @12 = (@10*@8) */
  w12  = (w10*w08);
  /* #24: @12 = (@12+@1) */
  w12 += w01;
  /* #25: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #26: output[0][1] = @12 */
  if (res[0]) res[0][1] = w12;
  /* #27: @13 = zeros(4x2,6nz) */
  casadi_clear(w13, 6);
  /* #28: @2 = (@2/@3) */
  w02 /= w03;
  /* #29: @4 = (@4/@5) */
  w04 /= w05;
  /* #30: @14 = ones(4x1,2nz) */
  casadi_fill(w14, 2, 1.);
  /* #31: {@12, NULL, NULL, NULL} = vertsplit(@14) */
  w12 = w14[0];
  /* #32: @7 = (@7*@12) */
  w07 *= w12;
  /* #33: @6 = (@6*@7) */
  w06 *= w07;
  /* #34: @4 = (@4*@6) */
  w04 *= w06;
  /* #35: @4 = (@8*@4) */
  w04  = (w08*w04);
  /* #36: @2 = (@2*@4) */
  w02 *= w04;
  /* #37: @2 = (@2/@5) */
  w02 /= w05;
  /* #38: @9 = (@9/@5) */
  w09 /= w05;
  /* #39: @9 = (@9*@6) */
  w09 *= w06;
  /* #40: @2 = (@2-@9) */
  w02 -= w09;
  /* #41: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #42: @9 = (@8*@2) */
  w09  = (w08*w02);
  /* #43: @10 = (@10*@4) */
  w10 *= w04;
  /* #44: @9 = (@9+@10) */
  w09 += w10;
  /* #45: @9 = (@11*@9) */
  w09  = (w11*w09);
  /* #46: @14 = vertcat(@2, @9) */
  rr=w14;
  *rr++ = w02;
  *rr++ = w09;
  /* #47: (@13[:6:3] = @14) */
  for (rr=w13+0, cs=w14; rr!=w13+6; rr+=3) *rr = *cs++;
  /* #48: @2 = ones(4x1,1nz) */
  w02 = 1.;
  /* #49: {NULL, @9, NULL, NULL} = vertsplit(@2) */
  w09 = w02;
  /* #50: @9 = (@9/@3) */
  w09 /= w03;
  /* #51: @9 = (@9/@5) */
  w09 /= w05;
  /* #52: @9 = (@0*@9) */
  w09  = (w00*w09);
  /* #53: @5 = (@8*@9) */
  w05  = (w08*w09);
  /* #54: @5 = (@11*@5) */
  w05  = (w11*w05);
  /* #55: @14 = vertcat(@9, @5) */
  rr=w14;
  *rr++ = w09;
  *rr++ = w05;
  /* #56: (@13[1:7:3] = @14) */
  for (rr=w13+1, cs=w14; rr!=w13+7; rr+=3) *rr = *cs++;
  /* #57: @9 = ones(4x1,1nz) */
  w09 = 1.;
  /* #58: {NULL, NULL, @5, NULL} = vertsplit(@9) */
  w05 = w09;
  /* #59: @0 = (@0*@5) */
  w00 *= w05;
  /* #60: @9 = (@0-@5) */
  w09  = (w00-w05);
  /* #61: @8 = (@8*@9) */
  w08 *= w09;
  /* #62: @8 = (@8+@5) */
  w08 += w05;
  /* #63: @11 = (@11*@8) */
  w11 *= w08;
  /* #64: @14 = vertcat(@0, @11) */
  rr=w14;
  *rr++ = w00;
  *rr++ = w11;
  /* #65: (@13[2:8:3] = @14) */
  for (rr=w13+2, cs=w14; rr!=w13+8; rr+=3) *rr = *cs++;
  /* #66: output[1][0] = @13 */
  casadi_copy(w13, 6, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_learned_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int battery_learned_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_learned_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_learned_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int battery_learned_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_learned_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void battery_learned_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void battery_learned_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int battery_learned_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int battery_learned_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real battery_learned_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_learned_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_learned_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_learned_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_learned_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int battery_learned_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 21;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_learned_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 21*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
