/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) battery_nominal_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[7] = {2, 2, 0, 1, 2, 0, 0};
static const casadi_int casadi_s1[7] = {2, 2, 0, 2, 2, 0, 1};
static const casadi_int casadi_s2[3] = {2, 1, 1};
static const casadi_int casadi_s3[3] = {2, 2, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* battery_nominal_expl_vde_forw:(i0[2],i1[2x2],i2[2x2],i3[2],i4)->(o0[2],o1[2x2,2nz],o2[2x2,2nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, *w18=w+18, *w19=w+22, *w20=w+24, *w21=w+26;
  const casadi_real *cs;
  /* #0: @0 = 4.08805e-06 */
  w00 = 4.0880503144654089e-06;
  /* #1: @1 = 1.024 */
  w01 = 1.0240000000000000e+00;
  /* #2: @2 = input[4][0] */
  w02 = arg[4] ? arg[4][0] : 0;
  /* #3: @3 = sq(@2) */
  w03 = casadi_sq( w02 );
  /* #4: @1 = (@1*@3) */
  w01 *= w03;
  /* #5: @3 = 3500 */
  w03 = 3500.;
  /* #6: @4 = 0.00668451 */
  w04 = 6.6845076098596048e-03;
  /* #7: @5 = input[3][0] */
  w05 = arg[3] ? arg[3][0] : 0;
  /* #8: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #9: @5 = (@3*@5) */
  w05  = (w03*w05);
  /* #10: @6 = 0.97 */
  w06 = 9.6999999999999997e-01;
  /* #11: @7 = 0.99 */
  w07 = 9.8999999999999999e-01;
  /* #12: @8 = input[0][0] */
  w08 = arg[0] ? arg[0][0] : 0;
  /* #13: @9 = input[3][1] */
  w09 = arg[3] ? arg[3][1] : 0;
  /* #14: @10 = 1 */
  w10 = 1.;
  /* #15: @11 = 2500 */
  w11 = 2500.;
  /* #16: @12 = 0.001 */
  w12 = 1.0000000000000000e-03;
  /* #17: @12 = (@12+@5) */
  w12 += w05;
  /* #18: @11 = (@11/@12) */
  w11 /= w12;
  /* #19: @13 = (-@11) */
  w13 = (- w11 );
  /* #20: @13 = exp(@13) */
  w13 = exp( w13 );
  /* #21: @10 = (@10-@13) */
  w10 -= w13;
  /* #22: @9 = (@9/@10) */
  w09 /= w10;
  /* #23: @14 = (@9/@12) */
  w14  = (w09/w12);
  /* #24: @15 = (@8+@14) */
  w15  = (w08+w14);
  /* #25: @15 = (@7*@15) */
  w15  = (w07*w15);
  /* #26: @16 = (@15-@8) */
  w16  = (w15-w08);
  /* #27: @17 = (@16*@13) */
  w17  = (w16*w13);
  /* #28: @17 = (@17+@8) */
  w17 += w08;
  /* #29: @17 = (@6*@17) */
  w17  = (w06*w17);
  /* #30: @17 = (@17-@15) */
  w17 -= w15;
  /* #31: @15 = (@5*@17) */
  w15  = (w05*w17);
  /* #32: @1 = (@1-@15) */
  w01 -= w15;
  /* #33: @1 = (@0*@1) */
  w01  = (w00*w01);
  /* #34: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #35: @1 = 100800 */
  w01 = 100800.;
  /* #36: @2 = (@2/@1) */
  w02 /= w01;
  /* #37: @2 = (-@2) */
  w02 = (- w02 );
  /* #38: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #39: @18 = input[1][0] */
  casadi_copy(arg[1], 4, w18);
  /* #40: {@19, @20} = horzsplit(@18) */
  casadi_copy(w18, 2, w19);
  casadi_copy(w18+2, 2, w20);
  /* #41: {@2, NULL} = vertsplit(@19) */
  w02 = w19[0];
  /* #42: @1 = (@7*@2) */
  w01  = (w07*w02);
  /* #43: @15 = (@1-@2) */
  w15  = (w01-w02);
  /* #44: @15 = (@13*@15) */
  w15  = (w13*w15);
  /* #45: @15 = (@15+@2) */
  w15 += w02;
  /* #46: @15 = (@6*@15) */
  w15  = (w06*w15);
  /* #47: @15 = (@15-@1) */
  w15 -= w01;
  /* #48: @15 = (@5*@15) */
  w15  = (w05*w15);
  /* #49: @15 = (@0*@15) */
  w15  = (w00*w15);
  /* #50: @15 = (-@15) */
  w15 = (- w15 );
  /* #51: output[1][0] = @15 */
  if (res[1]) res[1][0] = w15;
  /* #52: {@15, NULL} = vertsplit(@20) */
  w15 = w20[0];
  /* #53: @1 = (@7*@15) */
  w01  = (w07*w15);
  /* #54: @2 = (@1-@15) */
  w02  = (w01-w15);
  /* #55: @2 = (@13*@2) */
  w02  = (w13*w02);
  /* #56: @2 = (@2+@15) */
  w02 += w15;
  /* #57: @2 = (@6*@2) */
  w02  = (w06*w02);
  /* #58: @2 = (@2-@1) */
  w02 -= w01;
  /* #59: @2 = (@5*@2) */
  w02  = (w05*w02);
  /* #60: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #61: @2 = (-@2) */
  w02 = (- w02 );
  /* #62: output[1][1] = @2 */
  if (res[1]) res[1][1] = w02;
  /* #63: @20 = zeros(2x2,2nz) */
  casadi_clear(w20, 2);
  /* #64: @2 = ones(2x1,1nz) */
  w02 = 1.;
  /* #65: {@1, NULL} = vertsplit(@2) */
  w01 = w02;
  /* #66: @4 = (@4*@1) */
  w04 *= w01;
  /* #67: @3 = (@3*@4) */
  w03 *= w04;
  /* #68: @17 = (@17*@3) */
  w17 *= w03;
  /* #69: @9 = (@9/@10) */
  w09 /= w10;
  /* #70: @11 = (@11/@12) */
  w11 /= w12;
  /* #71: @11 = (@11*@3) */
  w11 *= w03;
  /* #72: @11 = (@13*@11) */
  w11  = (w13*w11);
  /* #73: @9 = (@9*@11) */
  w09 *= w11;
  /* #74: @9 = (@9/@12) */
  w09 /= w12;
  /* #75: @14 = (@14/@12) */
  w14 /= w12;
  /* #76: @14 = (@14*@3) */
  w14 *= w03;
  /* #77: @9 = (@9-@14) */
  w09 -= w14;
  /* #78: @9 = (@7*@9) */
  w09  = (w07*w09);
  /* #79: @14 = (@13*@9) */
  w14  = (w13*w09);
  /* #80: @16 = (@16*@11) */
  w16 *= w11;
  /* #81: @14 = (@14+@16) */
  w14 += w16;
  /* #82: @14 = (@6*@14) */
  w14  = (w06*w14);
  /* #83: @14 = (@14-@9) */
  w14 -= w09;
  /* #84: @14 = (@5*@14) */
  w14  = (w05*w14);
  /* #85: @17 = (@17+@14) */
  w17 += w14;
  /* #86: @17 = (@0*@17) */
  w17  = (w00*w17);
  /* #87: @17 = (-@17) */
  w17 = (- w17 );
  /* #88: (@20[0] = @17) */
  for (rr=w20+0, cs=(&w17); rr!=w20+1; rr+=1) *rr = *cs++;
  /* #89: @17 = ones(2x1,1nz) */
  w17 = 1.;
  /* #90: {NULL, @14} = vertsplit(@17) */
  w14 = w17;
  /* #91: @14 = (@14/@10) */
  w14 /= w10;
  /* #92: @14 = (@14/@12) */
  w14 /= w12;
  /* #93: @14 = (@7*@14) */
  w14  = (w07*w14);
  /* #94: @12 = (@13*@14) */
  w12  = (w13*w14);
  /* #95: @12 = (@6*@12) */
  w12  = (w06*w12);
  /* #96: @12 = (@12-@14) */
  w12 -= w14;
  /* #97: @12 = (@5*@12) */
  w12  = (w05*w12);
  /* #98: @12 = (@0*@12) */
  w12  = (w00*w12);
  /* #99: @12 = (-@12) */
  w12 = (- w12 );
  /* #100: (@20[1] = @12) */
  for (rr=w20+1, cs=(&w12); rr!=w20+2; rr+=1) *rr = *cs++;
  /* #101: @19 = @20' */
  casadi_trans(w20,casadi_s1, w19, casadi_s0, iw);
  /* #102: @18 = input[2][0] */
  casadi_copy(arg[2], 4, w18);
  /* #103: {@20, @21} = horzsplit(@18) */
  casadi_copy(w18, 2, w20);
  casadi_copy(w18+2, 2, w21);
  /* #104: {@12, NULL} = vertsplit(@20) */
  w12 = w20[0];
  /* #105: @14 = (@7*@12) */
  w14  = (w07*w12);
  /* #106: @10 = (@14-@12) */
  w10  = (w14-w12);
  /* #107: @10 = (@13*@10) */
  w10  = (w13*w10);
  /* #108: @10 = (@10+@12) */
  w10 += w12;
  /* #109: @10 = (@6*@10) */
  w10  = (w06*w10);
  /* #110: @10 = (@10-@14) */
  w10 -= w14;
  /* #111: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #112: @10 = (@0*@10) */
  w10  = (w00*w10);
  /* #113: @10 = (-@10) */
  w10 = (- w10 );
  /* #114: @22 = 00 */
  /* #115: @14 = vertcat(@10, @22) */
  rr=(&w14);
  *rr++ = w10;
  /* #116: {@10, NULL} = vertsplit(@21) */
  w10 = w21[0];
  /* #117: @7 = (@7*@10) */
  w07 *= w10;
  /* #118: @12 = (@7-@10) */
  w12  = (w07-w10);
  /* #119: @13 = (@13*@12) */
  w13 *= w12;
  /* #120: @13 = (@13+@10) */
  w13 += w10;
  /* #121: @6 = (@6*@13) */
  w06 *= w13;
  /* #122: @6 = (@6-@7) */
  w06 -= w07;
  /* #123: @5 = (@5*@6) */
  w05 *= w06;
  /* #124: @0 = (@0*@5) */
  w00 *= w05;
  /* #125: @0 = (-@0) */
  w00 = (- w00 );
  /* #126: @5 = vertcat(@0, @22) */
  rr=(&w05);
  *rr++ = w00;
  /* #127: @21 = horzcat(@14, @5) */
  rr=w21;
  *rr++ = w14;
  *rr++ = w05;
  /* #128: @19 = (@19+@21) */
  for (i=0, rr=w19, cs=w21; i<2; ++i) (*rr++) += (*cs++);
  /* #129: output[2][0] = @19 */
  casadi_copy(w19, 2, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real battery_nominal_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s3;
    case 3: return casadi_s2;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 28;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 28*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
