/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) battery_nominal_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[7] = {4, 1, 0, 3, 0, 2, 3};

/* battery_nominal_expl_vde_adj:(i0[2],i1[2],i2[2],i3)->(o0[4x1,3nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w00, w01, w02, w03, w04, w05, w06, w07, *w08=w+8, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16;
  /* #0: @0 = 2500 */
  w00 = 2500.;
  /* #1: @1 = 0.001 */
  w01 = 1.0000000000000000e-03;
  /* #2: @2 = 3500 */
  w02 = 3500.;
  /* #3: @3 = 0.00668451 */
  w03 = 6.6845076098596048e-03;
  /* #4: @4 = input[2][0] */
  w04 = arg[2] ? arg[2][0] : 0;
  /* #5: @4 = (@3*@4) */
  w04  = (w03*w04);
  /* #6: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #7: @1 = (@1+@4) */
  w01 += w04;
  /* #8: @0 = (@0/@1) */
  w00 /= w01;
  /* #9: @5 = (-@0) */
  w05 = (- w00 );
  /* #10: @5 = exp(@5) */
  w05 = exp( w05 );
  /* #11: @6 = 0.97 */
  w06 = 9.6999999999999997e-01;
  /* #12: @7 = 4.08805e-06 */
  w07 = 4.0880503144654089e-06;
  /* #13: @8 = input[1][0] */
  casadi_copy(arg[1], 2, w08);
  /* #14: {@9, NULL} = vertsplit(@8) */
  w09 = w08[0];
  /* #15: @7 = (@7*@9) */
  w07 *= w09;
  /* #16: @4 = (@4*@7) */
  w04 *= w07;
  /* #17: @9 = (@6*@4) */
  w09  = (w06*w04);
  /* #18: @10 = (@5*@9) */
  w10  = (w05*w09);
  /* #19: @11 = (@10-@9) */
  w11  = (w10-w09);
  /* #20: @12 = 0.99 */
  w12 = 9.8999999999999999e-01;
  /* #21: @4 = (@4-@10) */
  w04 -= w10;
  /* #22: @4 = (@12*@4) */
  w04  = (w12*w04);
  /* #23: @11 = (@11+@4) */
  w11 += w04;
  /* #24: output[0][0] = @11 */
  if (res[0]) res[0][0] = w11;
  /* #25: @0 = (@0/@1) */
  w00 /= w01;
  /* #26: @11 = input[0][0] */
  w11 = arg[0] ? arg[0][0] : 0;
  /* #27: @10 = input[2][1] */
  w10 = arg[2] ? arg[2][1] : 0;
  /* #28: @13 = 1 */
  w13 = 1.;
  /* #29: @13 = (@13-@5) */
  w13 -= w05;
  /* #30: @10 = (@10/@13) */
  w10 /= w13;
  /* #31: @14 = (@10/@1) */
  w14  = (w10/w01);
  /* #32: @15 = (@11+@14) */
  w15  = (w11+w14);
  /* #33: @12 = (@12*@15) */
  w12 *= w15;
  /* #34: @15 = (@12-@11) */
  w15  = (w12-w11);
  /* #35: @9 = (@15*@9) */
  w09  = (w15*w09);
  /* #36: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #37: @10 = (@10/@13) */
  w10 /= w13;
  /* #38: @16 = (@4/@1) */
  w16  = (w04/w01);
  /* #39: @10 = (@10*@16) */
  w10 *= w16;
  /* #40: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #41: @9 = (@9-@10) */
  w09 -= w10;
  /* #42: @0 = (@0*@9) */
  w00 *= w09;
  /* #43: @0 = (@2*@0) */
  w00  = (w02*w00);
  /* #44: @0 = (-@0) */
  w00 = (- w00 );
  /* #45: @14 = (@14/@1) */
  w14 /= w01;
  /* #46: @14 = (@14*@4) */
  w14 *= w04;
  /* #47: @14 = (@2*@14) */
  w14  = (w02*w14);
  /* #48: @0 = (@0-@14) */
  w00 -= w14;
  /* #49: @15 = (@15*@5) */
  w15 *= w05;
  /* #50: @15 = (@15+@11) */
  w15 += w11;
  /* #51: @6 = (@6*@15) */
  w06 *= w15;
  /* #52: @6 = (@6-@12) */
  w06 -= w12;
  /* #53: @6 = (@6*@7) */
  w06 *= w07;
  /* #54: @2 = (@2*@6) */
  w02 *= w06;
  /* #55: @0 = (@0-@2) */
  w00 -= w02;
  /* #56: @3 = (@3*@0) */
  w03 *= w00;
  /* #57: output[0][1] = @3 */
  if (res[0]) res[0][1] = w03;
  /* #58: @16 = (@16/@13) */
  w16 /= w13;
  /* #59: output[0][2] = @16 */
  if (res[0]) res[0][2] = w16;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real battery_nominal_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 18;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 18*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
