/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) battery_nominal_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};

/* battery_nominal_expl_ode_fun:(i0[2],i1[2],i2)->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  /* #0: @0 = 4.08805e-06 */
  w00 = 4.0880503144654089e-06;
  /* #1: @1 = 1.024 */
  w01 = 1.0240000000000000e+00;
  /* #2: @2 = input[2][0] */
  w02 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = sq(@2) */
  w03 = casadi_sq( w02 );
  /* #4: @1 = (@1*@3) */
  w01 *= w03;
  /* #5: @3 = 3500 */
  w03 = 3500.;
  /* #6: @4 = 0.00668451 */
  w04 = 6.6845076098596048e-03;
  /* #7: @5 = input[1][0] */
  w05 = arg[1] ? arg[1][0] : 0;
  /* #8: @4 = (@4*@5) */
  w04 *= w05;
  /* #9: @3 = (@3*@4) */
  w03 *= w04;
  /* #10: @4 = 0.97 */
  w04 = 9.6999999999999997e-01;
  /* #11: @5 = 0.99 */
  w05 = 9.8999999999999999e-01;
  /* #12: @6 = input[0][0] */
  w06 = arg[0] ? arg[0][0] : 0;
  /* #13: @7 = input[1][1] */
  w07 = arg[1] ? arg[1][1] : 0;
  /* #14: @8 = 1 */
  w08 = 1.;
  /* #15: @9 = 2500 */
  w09 = 2500.;
  /* #16: @10 = 0.001 */
  w10 = 1.0000000000000000e-03;
  /* #17: @10 = (@10+@3) */
  w10 += w03;
  /* #18: @9 = (@9/@10) */
  w09 /= w10;
  /* #19: @9 = (-@9) */
  w09 = (- w09 );
  /* #20: @9 = exp(@9) */
  w09 = exp( w09 );
  /* #21: @8 = (@8-@9) */
  w08 -= w09;
  /* #22: @7 = (@7/@8) */
  w07 /= w08;
  /* #23: @7 = (@7/@10) */
  w07 /= w10;
  /* #24: @7 = (@6+@7) */
  w07  = (w06+w07);
  /* #25: @5 = (@5*@7) */
  w05 *= w07;
  /* #26: @7 = (@5-@6) */
  w07  = (w05-w06);
  /* #27: @7 = (@7*@9) */
  w07 *= w09;
  /* #28: @7 = (@7+@6) */
  w07 += w06;
  /* #29: @4 = (@4*@7) */
  w04 *= w07;
  /* #30: @4 = (@4-@5) */
  w04 -= w05;
  /* #31: @3 = (@3*@4) */
  w03 *= w04;
  /* #32: @1 = (@1-@3) */
  w01 -= w03;
  /* #33: @0 = (@0*@1) */
  w00 *= w01;
  /* #34: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #35: @0 = 100800 */
  w00 = 100800.;
  /* #36: @2 = (@2/@0) */
  w02 /= w00;
  /* #37: @2 = (-@2) */
  w02 = (- w02 );
  /* #38: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void battery_nominal_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int battery_nominal_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real battery_nominal_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* battery_nominal_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* battery_nominal_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 11;
  return 0;
}

CASADI_SYMBOL_EXPORT int battery_nominal_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 11*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
